numbers=set()
a=int(input("enter the number:"))
b=int(input("enter the number:"))
c=int(input("enter the number:"))
d=int(input("enter the number:"))
e=int(input("enter the number:"))
f=int(input("enter the number:"))
g=int(input("enter the number:"))
h=int(input("enter the number:"))
numbers.add(a)
numbers.add(b)
numbers.add(c)


print(numbers)
